[workspace]

members = [
    "rewind-core",
    "rewind-snapshot",
    "rewind-whvp",
    "rewind-bochs",
    "rewind-kvm",
    "rewind-system",
    "rewind-tui",
    "rewind-cli",
    "whvp-sys",
]

default-members = [
]

exclude = [
    "examples",
    "vendor",
]

